namespace RL26_Database_Editor
{
    /// <summary>
    /// String Array Class.
    /// </summary>
    /// <remarks>
    ///   RL26 Database Editor. Written by Wouldubeinta
    ///   Copyright (C) 2025 Wouldy Mods.
    ///   
    ///   This program is free software; you can redistribute it and/or
    ///   modify it under the terms of the GNU General Public License
    ///   as published by the Free Software Foundation; either version 3
    ///   of the License, or (at your option) any later version.
    ///   
    ///   This program is distributed in the hope that it will be useful,
    ///   but WITHOUT ANY WARRANTY; without even the implied warranty of
    ///   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    ///   GNU General Public License for more details.
    ///   
    ///   You should have received a copy of the GNU General Public License
    ///   along with this program; if not, write to the Free Software
    ///   Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
    /// 
    ///   The author may be contacted at:
    ///   Discord: Wouldubeinta
    /// </remarks>
    /// <history>
    /// [Wouldubeinta]	   23/09/2025	Created
    /// </history>
    public class StringArrays
    {
        public static string[] CountryOfBirth = new string[196]
        {
            "Austrialia",
            "Belgium",
            "Canada",
            "Chile",
            "China",
            "Congo",
            "Cook Islands",
            "Czech Republic",
            "Denmark",
            "England",
            "Estonia",
            "Fiji",
            "France",
            "Germany",
            "Greece",
            "Hungary",
            "Ireland",
            "Italy",
            "Jamaica",
            "Latvia",
            "Lebanon",
            "Malaysia",
            "Malta",
            "Mexico",
            "Morocco",
            "Netherlands",
            "New Zealand",
            "Nigeria",
            "Norway",
            "Papua New Guinea",
            "Philippines",
            "Russia",
            "Samoa",
            "Scotland",
            "Serbia",
            "South Africa",
            "Spain",
            "Sweden",
            "Switzerland",
            "Tonga",
            "United States",
            "Ukraine",
            "Wales",
            "Zimbabwe",
            "Afghanistan",
            "Albania",
            "Algeria",
            "Andorra",
            "Angola",
            "Antigua",
            "Argentina",
            "Armenia",
            "Austria",
            "Azerbaijan",
            "Bahamas",
            "Bahrain",
            "Bangladesh",
            "Barbados",
            "Barbuda",
            "Belarus",
            "Belize",
            "Benin",
            "Bermuda",
            "Bhutan",
            "Bolivia",
            "Bosnia And Herzegovina",
            "Botswana",
            "Brazil",
            "Brunei",
            "Bulgaria",
            "Burkina",
            "Burundi",
            "Cambodia",
            "Cameroon",
            "Cape Verde",
            "Chad",
            "Colombia",
            "Comoros",
            "Costa Rica",
            "Croatia",
            "Cuba",
            "Cyprus",
            "Djibouti",
            "Dominica",
            "Dominican Republic",
            "Ecuador",
            "Egypt",
            "El Salvador",
            "Equatorial Guinea",
            "Eritrea",
            "Ethiopia",
            "Finland",
            "Gabon",
            "Gambia",
            "Georgia",
            "Ghana",
            "Grenada",
            "Guatemala",
            "Guinea",
            "Guinea-Bissau",
            "Guyana",
            "Haiti",
            "Honduras",
            "Hong Kong",
            "Iceland",
            "India",
            "Indonesia",
            "Iran",
            "Iraq",
            "Israel",
            "Côte D’Ivoire",
            "Japan",
            "Jordan",
            "Kazakhstan",
            "Kenya",
            "Kiribati",
            "Kuwait",
            "Kyrgyzstan",
            "Lesotho",
            "Liberia",
            "Libya",
            "Liechtenstein",
            "Lithuania",
            "Luxembourg",
            "Macedonia",
            "Madagascar",
            "Malawi",
            "Maldives",
            "Mali",
            "Marshall Islands",
            "Mauritania",
            "Mauritius",
            "Micronesia",
            "Moldova",
            "Monaco",
            "Mongolia",
            "Montenegro",
            "Mozambique",
            "Myanmar",
            "Namibia",
            "Nauru",
            "Nepal",
            "Nicaragua",
            "Niger",
            "Niue",
            "Oman",
            "Pakistan",
            "Palau",
            "Panama",
            "Paraguay",
            "Peru",
            "Poland",
            "Portugal",
            "Qatar",
            "Romania",
            "Rwanda",
            "St.Kitts And Nevis",
            "St.Lucia",
            "St.Vincent",
            "San Marino",
            "Saudi Arabia",
            "Senegal",
            "Seychelles",
            "Sierra Leone",
            "Singapore",
            "Slovakia",
            "Slovenia",
            "Solomon Islands",
            "Somalia",
            "South Korea",
            "South Sudan",
            "Sri Lanka",
            "Sudan",
            "Suriname",
            "Swaziland",
            "Syria",
            "Tajikistan",
            "Tanzania",
            "Thailand",
            "Timor-Leste",
            "Togo",
            "Trinidad And Tobago",
            "Tunisia",
            "Turkey",
            "Turkmenistan",
            "Tuvalu",
            "Uganda",
            "United Arab Emirates",
            "Uruguay",
            "Uzbekistan",
            "Vanuatu",
            "Venezuela",
            "Vietnam",
            "West Indies",
            "Yemen",
            "Zambia"
        };

        public static string[] RepCountry = new string[44]
        {
            "Austrialia",
            "Belgium",
            "Canada",
            "Chile",
            "Mainland China and Hong Kong",
            "Congo",
            "Cook Islands",
            "Czech Republic",
            "Denmark",
            "England",
            "Estonia",
            "Fiji",
            "France",
            "Germany",
            "Greece",
            "Hungary",
            "Ireland",
            "Italy",
            "Jamaica",
            "Latvia",
            "Lebanon",
            "Malaysia",
            "Malta",
            "Mexico",
            "Morocco",
            "Netherlands",
            "New Zealand",
            "Nigeria",
            "Norway",
            "Papua New Guinea",
            "Philippines",
            "Russia",
            "Samoa",
            "Scotland",
            "Serbia",
            "South Africa",
            "Spain",
            "Sweden",
            "Switzerland",
            "Tonga",
            "United States",
            "Ukraine",
            "Wales",
            "Zimbabwe"
        };

        public static string[] Stadiums = new string[89]
        {
            "Allianz Stadium",
            "Suncorp Stadium",
            "Belmore Sports Ground",
            "Brookvale Oval",
            "Campbelltown Sport Stadium",
            "GIO Stadium Canberra",
            "Sewell Group Craven Park",
            "Shark Stadium",
            "Halliwell Jones Stadium",
            "AMT Headingley Rugby Stadium",
            "McDonald Jones Stadium",
            "MKM Stadium",
            "Accu Stadium",
            "Jubilee Stadium",
            "Totally Wicked Stadium",
            "Allegiant Stadium",
            "Leichhardt Oval",
            "Leigh Sports Village",
            "AAMI Park",
            "Kayo Stadium",
            "Go Media Stadium",
            "Queensland Country Bank Stadium",
            "Old Trafford Stadium",
            "BlueBet Stadium",
            "HBF Park",
            "Optus Stadium",
            "Cbus Super Stadium",
            "Salford Community Stadium",
            "Sydney Cricket Oval",
            "Stade Gilbert Brutus",
            "Accor Stadium",
            "DIY Kitchens Stadiums",
            "CommBank Stadium",
            "Wheldon Road Stadium",
            "Brick Community Stadium",
            "WIN Stadium",
            "Northern Competitions Stadium",
            "Mount Pleasant Stadium",
            "Bartercard Odsal Stadium",
            "Eco Power Stadium",
            "The Millennium Stadium",
            "The Shay Stadium",
            "South Leeds Stadium",
            "Boundary Park",
            "Steel City Stadium",
            "Stadium de Toulouse",
            "DCBL Stadium",
            "York Stadium Leisure Complex",
            "The Memorial Ground",
            "FLAIR Stadium",
            "Victoria Pleasure Grounds",
            "Cougar Park",
            "Alexander Stadium",
            "Crow Trees Ground",
            "Eirias Stadium",
            "Crown Oil Arena",
            "Salford Community Stadium",
            "The Ortus REC",
            "Derwent Park",
            "Henson Park",
            "North Sydney Oval",
            "Kellyville Memorial Park",
            "Penrith Reserve",
            "Redfern Oval",
            "Blacktown Sporting Complex",
            "Langlands Park",
            "Pizzey Park",
            "Browne Park",
            "Bendigo Bank Oval",
            "BB Print Stadium",
            "Barlow Park",
            "Nundah Rugby Park",
            "Santos National Football Stadium",
            "Davies Park",
            "Sunshine Coast Stadium",
            "Kirwan Oval",
            "Seagulls Sports Complex",
            "Toowoomba Sports Ground",
            "Manly West Park",
            "Eden Park",
            "FMG Stadium Waikato",
            "Sky Stadium",
            "Appollo Projects Stadium",
            "Wembley Stadium",
            "Cherry Red Records Stadium",
            "TIO Stadium (Marrara Stadium)",
            "Carrington Park",
            "Glen Willow Regional Sports Stadium",
            "Polytec Stadium"
        };

        public static string[] Supporters = new string[129]
        {
            "BigAnt",
            "Nacon",
            "Broncos",
            "Bulldogs",
            "Cowboys",
            "Dragons",
            "Eels",
            "Knights",
            "Panthers",
            "Rabbitohs",
            "Raiders",
            "Roosters",
            "Sea Eagles",
            "Sharks",
            "Storm",
            "Tigers",
            "Titans",
            "Warriors",
            "Castleford",
            "Catalans",
            "Huddersfield",
            "Hull FC",
            "Leeds",
            "Leigh",
            "Salford",
            "Saint Helens",
            "Wakefield",
            "Warrington",
            "Widnes",
            "Wigan",
            "London Broncos",
            "Batley",
            "Bradford",
            "Sheffield",
            "Featherstone",
            "Halifax",
            "Hornets",
            "Hull KR",
            "Lions",
            "Oldham",
            "Olympique",
            "Dewsbury",
            "Gloucestershire",
            "Coventry",
            "Keighley",
            "North Wales",
            "Doncaster",
            "Hawks",
            "Iron Men",
            "York City",
            "Oxford",
            "Barrow",
            "London Skolars",
            "Hemel",
            "Newcastle",
            "Whitehaven",
            "Wolf Pack",
            "Workington",
            "North Sydney Bears",
            "Illawarra",
            "Jets",
            "Wentworthville",
            "Mounties",
            "Wyong Roos",
            "Blacktown",
            "Burleigh Bears",
            "Blackhawks",
            "Capras",
            "Mackay Cutters",
            "Devils",
            "Redcliffe",
            "Falcons",
            "Wynnum Manly Seagulls",
            "Hunters",
            "Ipswich",
            "Magpies",
            "Pride",
            "Tweed Heads",
            "Eastern Suburbs",
            "World Allstars",
            "City",
            "Country",
            "Indigenous Allstars",
            "New South Wales",
            "Queensland",
            "Australia (Alt)",
            "New Zealand (Alt)",
            "England (Alt)",
            "Belgium",
            "Canada",
            "Cook Islands",
            "Czech Republic",
            "Denmark",
            "Fiji",
            "France",
            "Germany",
            "Greece",
            "Nertherlands",
            "Hungary",
            "Ireland",
            "Italy",
            "Jamaica",
            "Latvia",
            "Lebanon",
            "Malta",
            "Morocco",
            "Norway",
            "Papua New Guinea",
            "Russia",
            "Samoa",
            "Scotland",
            "Serbia",
            "South Africa",
            "Spain",
            "Sweden",
            "Tonga",
            "Ukraine",
            "USA",
            "Wales",
            "Pro Team",
            "Barrow Raiders Women",
            "Huddersfield Giants Women",
            "Leeds Rhinos Women",
            "Leigh Leopards Women",
            "St. Helens Saints Women",
            "York Valkyrie Women",
            "Warrington Wolves Women",
            "Wigan Warriors Women",
            "Custom"
        };

        public static string[] Logos = new string[262]
        {
            "Broncos",
            "Bulldogs",
            "Cowboys",
            "Dragons",
            "Eels",
            "Knights",
            "Panthers",
            "Rabbitohs",
            "Raiders",
            "Roosters",
            "Sea Eagles",
            "Sharks",
            "Storm",
            "Tigers",
            "Titans",
            "Warriors",
            "Castleford",
            "Catalans",
            "Huddersfield",
            "Hull F.C",
            "Leeds",
            "Leigh",
            "Salford",
            "Saint Helens",
            "Wakefield",
            "Warrington",
            "Widnes",
            "Wigan",
            "North Sydney Bears",
            "NSW Blackhawks",
            "Cutters",
            "Jets",
            "Wentworthville",
            "Mounties",
            "Wyong Roos",
            "Blacktown",
            "Burleigh Bears",
            "QLD Blackhawks",
            "Capras",
            "Mackay Cutters",
            "Devils",
            "Dolphins",
            "Falcons",
            "Wynnum Manly Seagulls",
            "Hunters",
            "Ipswich Jets",
            "Magpies",
            "Pride",
            "Tweed Heads",
            "Eastern Suburbs",
            "London Broncos",
            "Batley",
            "Bradford",
            "Leigh",
            "Sheffield",
            "Featherstone",
            "Halifax",
            "Rochdale",
            "Hull Rovers",
            "Swinton",
            "Oldham",
            "Olympique",
            "Dewsbury",
            "Gloucestershire",
            "Coventry",
            "Keighley",
            "North Wales",
            "Doncaster",
            "Hunslet",
            "Iron Men",
            "York City",
            "Oxford",
            "Barrow",
            "London Skolars",
            "Hemel",
            "Newcastle Thunder",
            "Whitehaven",
            "Wolf Pack",
            "Workington",
            "Australia",
            "New Zealand",
            "England",
            "Belguim",
            "Canada",
            "Cook Islands",
            "Czech Republic",
            "Denmark",
            "Fiji",
            "France",
            "Germany",
            "Greece",
            "Holland",
            "Hungary",
            "Ireland",
            "Italy",
            "Jamaica",
            "Latvia",
            "Lebanon",
            "Malta",
            "Morocco",
            "Norway",
            "Papua New Guinea",
            "Russia",
            "Samoa",
            "Scotland",
            "Serbia",
            "South Africa",
            "Spain",
            "Sweden",
            "Tonga",
            "Ukraine",
            "USA",
            "Wales",
            "Australia(ALT)",
            "New Zealand(ALT)",
            "England(ALT)",
            "NSW Blues",
            "QLD Moroons",
            "World Allstars",
            "Indigenous Allstars",
            "City",
            "Country",
            "BigAnt Male",
            "BigAnt Female",
            "Trublu",
            "Custom Team",
            "F.C",
            "R.L.C",
            "R.L",
            "Gladiators",
            "Fleur De Lys",
            "T-Rex",
            "Yellow Shield",
            "Red Bulls",
            "Griffons",
            "Stags",
            "Eagle Shield",
            "RL Crowns",
            "Rams",
            "Wolves",
            "Snakes",
            "Ravens",
            "Fishes",
            "Swans",
            "Lion Shield",
            "Castle Fox",
            "Winged Blade",
            "Roses",
            "Armour",
            "Flames",
            "Blue Rose",
            "Lion Head",
            "Crowned",
            "Red Lion",
            "Redback",
            "Red Shield",
            "Blue Shield",
            "Sun Shield",
            "Blades",
            "Medallion",
            "Sword And Sun",
            "Ribbon",
            "Purple Shield",
            "Unicorn Shield",
            "Horse Shield",
            "Red Fleur De Lys",
            "Purple Crown",
            "Whales",
            "Wasps",
            "Bombers",
            "Workman",
            "Londoners",
            "Rangers",
            "Gorillas",
            "Jaguars",
            "Armadillos",
            "Blue Tongues",
            "Red Knight",
            "Tassie Tigers",
            "Yellow Bull",
            "Keas",
            "Irish",
            "Pirates",
            "Crocs",
            "Wombats",
            "Stringers",
            "Nuggets",
            "Braves",
            "R-Arrows",
            "Hurricanes",
            "Browns",
            "Torpedos",
            "Cockatoos",
            "Blue Rings",
            "Penguins",
            "Boars",
            "Cobras",
            "Phoenix",
            "Foxes",
            "cus_74.pc.png",
            "cus_75.pc.png",
            "cus_76.pc.png",
            "cus_77.pc.png",
            "cus_78.pc.png",
            "cus_79.pc.png",
            "cus_80.pc.png",
            "cus_81.pc.png",
            "cus_82.pc.png",
            "cus_83.pc.png",
            "cus_84.pc.png",
            "cus_85.pc.png",
            "cus_86.pc.png",
            "cus_87.pc.png",
            "cus_88.pc.png",
            "cus_89.pc.png",
            "cus_90.pc.png",
            "cus_91.pc.png",
            "cus_92.pc.png",
            "cus_93.pc.png",
            "cus_94.pc.png",
            "cus_95.pc.png",
            "cus_96.pc.png",
            "cus_97.pc.png",
            "cus_98.pc.png",
            "cus_99.pc.png",
            "cus_100.pc.png",
            "cus_101.pc.png",
            "cus_102.pc.png",
            "cus_103.pc.png",
            "cus_104.pc.png",
            "cus_105.pc.png",
            "cus_106.pc.png",
            "cus_107.pc.png",
            "cus_108.pc.png",
            "cus_109.pc.png",
            "cus_110.pc.png",
            "cus_111.pc.png",
            "cus_112.pc.png",
            "cus_113.pc.png",
            "cus_114.pc.png",
            "cus_115.pc.png",
            "cus_116.pc.png",
            "cus_117.pc.png",
            "cus_118.pc.png",
            "Australia Jillaroos",
            "Canada Ravens",
            "Cook Islands",
            "New Zealand Ferns",
            "PNG Orchids",
            "Fiji(ALT)",
            "France(ALT)",
            "Ireland(ALT)",
            "Italy(ALT)",
            "Lebanon(ALT)",
            "New Zealand Kiwis(ALT)",
            "PNG(ALT)",
            "Samoa(ALT)",
            "Scotland(ALT)",
            "Tonga(ALT)",
            "USA(ALT)",
            "Wales(ALT)",
            "Custom"
        };

        public static string[] LogosPNG = new string[281]
        {
            "nrl_broncos.pc.png",
            "nrl_bulldogs.pc.png",
            "nrl_cowboys.pc.png",
            "nrl_dolphins.pc.png",
            "nrl_dragons.pc.png",
            "nrl_eels.pc.png",
            "nrl_knights.pc.png",
            "nrl_panthers.pc.png",
            "nrl_rabbitohs.pc.png",
            "nrl_raiders.pc.png",
            "nrl_roosters.pc.png",
            "nrl_seaeagles.pc.png",
            "nrl_sharks.pc.png",
            "nrl_storm.pc.png",
            "nrl_tigers.pc.png",
            "nrl_titans.pc.png",
            "nrl_warriors.pc.png",
            "sl_castleford.pc.png",
            "sl_catalans.pc.png",
            "sl_huddersfield.pc.png",
            "sl_hullfc.pc.png",
            "sl_hullkr.pc.png",
            "sl_leeds.pc.png",
            "sl_leigh.pc.png",
            "sl_salford.pc.png",
            "sl_sthelens.pc.png",
            "sl_wakefield.pc.png",
            "sl_warrington.pc.png",
            "sl_widnes.pc.png",
            "sl_wigan.pc.png",
            "nsw_bears.pc.png",
            "nsw_blackhawks.pc.png",
            "nsw_cutters.pc.png",
            "nsw_jets.pc.png",
            "nsw_magpies.pc.png",
            "nsw_mounties.pc.png",
            "nsw_roos.pc.png",
            "nsw_seaeagles.pc.png",
            "nsw_westernsuburbs.pc.png",
            "qld_bears.pc.png",
            "qld_blackhawks.pc.png",
            "qld_capras.pc.png",
            "qld_clydesdales.pc.png",
            "qld_cutters.pc.png",
            "qld_devils.pc.png",
            "qld_dolphins.pc.png",
            "qld_falcons.pc.png",
            "qld_gullsmanly.pc.png",
            "qld_hunters.pc.png",
            "qld_jets.pc.png",
            "qld_magpies.pc.png",
            "qld_pride.pc.png",
            "qld_seagulls.pc.png",
            "qld_tigers.pc.png",
            "king_broncos.pc.png",
            "king_bulldogs.pc.png",
            "king_bulls.pc.png",
            "king_centurions.pc.png",
            "king_eagles.pc.png",
            "king_feather.pc.png",
            "king_halifax.pc.png",
            "king_hornets.pc.png",
            "king_hullkingston.pc.png",
            "king_lions.pc.png",
            "king_oldham.pc.png",
            "king_olympique.pc.png",
            "king_rams.pc.png",
            "king1_allgolds.pc.png",
            "king1_bears.pc.png",
            "king1_cougers.pc.png",
            "king1_crusaders.pc.png",
            "king1_doncaster.pc.png",
            "king1_hawks.pc.png",
            "king1_hurricanes.pc.png",
            "king1_ironmen.pc.png",
            "king1_knights.pc.png",
            "king1_oxford.pc.png",
            "king1_raiders.pc.png",
            "king1_skolars.pc.png",
            "king1_stags.pc.png",
            "king1_thunder.pc.png",
            "king1_vikings.pc.png",
            "king1_whitehaven.pc.png",
            "king1_wolfpack.pc.png",
            "king1_workington.pc.png",
            "slw_barrow.pc.png",
            "slw_huddersfield.pc.png",
            "slw_leeds.pc.png",
            "slw_leigh.pc.png",
            "slw_sthelens.pc.png",
            "slw_valkyrie.pc.png",
            "slw_warrington.pc.png",
            "slw_wigan.pc.png",
            "rep_allstars.pc.png",
            "rep_australia.pc.png",
            "rep_australia_2.pc.png",
            "rep_belguim.pc.png",
            "rep_bigant_male.pc.png",
            "rep_bigant_female.pc.png",
            "rep_canada.pc.png",
            "rep_city.pc.png",
            "rep_cookislands.pc.png",
            "rep_country.pc.png",
            "rep_czechrep.pc.png",
            "rep_denmark.pc.png",
            "rep_england.pc.png",
            "rep_england_2.pc.png",
            "rep_fiji.pc.png",
            "rep_fiji_2.pc.png",
            "rep_france.pc.png",
            "rep_france_2.pc.png",
            "rep_germany.pc.png",
            "rep_greece.pc.png",
            "rep_holland.pc.png",
            "rep_hungary.pc.png",
            "rep_indigenous.pc.png",
            "maori.pc.png",
            "rep_ireland.pc.png",
            "rep_ireland_2.pc.png",
            "rep_italy.pc.png",
            "rep_italy_2.pc.png",
            "rep_jamaica.pc.png",
            "rep_latvia.pc.png",
            "rep_lebanon.pc.png",
            "rep_lebanon_2.pc.png",
            "rep_malta.pc.png",
            "rep_morocco.pc.png",
            "rep_norway.pc.png",
            "rep_nsw.pc.png",
            "soow_nsw.pc.png",
            "rep_nz.pc.png",
            "rep_nz_2.pc.png",
            "rep_nz_3.pc.png",
            "rep_png.pc.png",
            "rep_png_2.pc.png",
            "rep_qld.pc.png",
            "soow_qld.pc.png",
            "rep_russia.pc.png",
            "rep_samoa.pc.png",
            "rep_samoa_2.pc.png",
            "rep_scotland.pc.png",
            "rep_scotland_2.pc.png",
            "rep_serbia.pc.png",
            "rep_southafrica.pc.png",
            "rep_spain.pc.png",
            "rep_sweden.pc.png",
            "rep_tonga.pc.png",
            "rep_tonga_2.pc.png",
            "rep_ukraine.pc.png",
            "rep_usa.pc.png",
            "rep_usa_2.pc.png",
            "rep_wales.pc.png",
            "rep_wales_2.pc.png",
            "aus_jillaroos.pc.png",
            "canada_ravens.pc.png",
            "cookislands.pc.png",
            "nz_ferns.pc.png",
            "png_orchids.pc.png",
            "custom.pc.png",
            "cus_01.pc.png",
            "cus_02.pc.png",
            "cus_03.pc.png",
            "cus_04.pc.png",
            "cus_05.pc.png",
            "cus_06.pc.png",
            "cus_07.pc.png",
            "cus_08.pc.png",
            "cus_09.pc.png",
            "cus_10.pc.png",
            "cus_11.pc.png",
            "cus_12.pc.png",
            "cus_13.pc.png",
            "cus_14.pc.png",
            "cus_15.pc.png",
            "cus_16.pc.png",
            "cus_17.pc.png",
            "cus_18.pc.png",
            "cus_19.pc.png",
            "cus_20.pc.png",
            "cus_21.pc.png",
            "cus_22.pc.png",
            "cus_23.pc.png",
            "cus_24.pc.png",
            "cus_25.pc.png",
            "cus_26.pc.png",
            "cus_27.pc.png",
            "cus_28.pc.png",
            "cus_29.pc.png",
            "cus_30.pc.png",
            "cus_31.pc.png",
            "cus_32.pc.png",
            "cus_33.pc.png",
            "cus_34.pc.png",
            "cus_35.pc.png",
            "cus_36.pc.png",
            "cus_37.pc.png",
            "cus_38.pc.png",
            "cus_39.pc.png",
            "cus_40.pc.png",
            "cus_41.pc.png",
            "cus_42.pc.png",
            "cus_43.pc.png",
            "cus_44.pc.png",
            "cus_45.pc.png",
            "cus_46.pc.png",
            "cus_47.pc.png",
            "cus_48.pc.png",
            "cus_49.pc.png",
            "cus_50.pc.png",
            "cus_51.pc.png",
            "cus_52.pc.png",
            "cus_53.pc.png",
            "cus_54.pc.png",
            "cus_55.pc.png",
            "cus_56.pc.png",
            "cus_57.pc.png",
            "cus_58.pc.png",
            "cus_59.pc.png",
            "cus_60.pc.png",
            "cus_61.pc.png",
            "cus_62.pc.png",
            "cus_63.pc.png",
            "cus_64.pc.png",
            "cus_65.pc.png",
            "cus_66.pc.png",
            "cus_67.pc.png",
            "cus_68.pc.png",
            "cus_69.pc.png",
            "cus_70.pc.png",
            "cus_71.pc.png",
            "cus_72.pc.png",
            "cus_73.pc.png",
            "cus_74.pc.png",
            "cus_75.pc.png",
            "cus_76.pc.png",
            "cus_77.pc.png",
            "cus_78.pc.png",
            "cus_79.pc.png",
            "cus_80.pc.png",
            "cus_81.pc.png",
            "cus_82.pc.png",
            "cus_83.pc.png",
            "cus_84.pc.png",
            "cus_85.pc.png",
            "cus_86.pc.png",
            "cus_87.pc.png",
            "cus_88.pc.png",
            "cus_89.pc.png",
            "cus_90.pc.png",
            "cus_91.pc.png",
            "cus_92.pc.png",
            "cus_93.pc.png",
            "cus_94.pc.png",
            "cus_95.pc.png",
            "cus_96.pc.png",
            "cus_97.pc.png",
            "cus_98.pc.png",
            "cus_99.pc.png",
            "cus_100.pc.png",
            "cus_101.pc.png",
            "cus_102.pc.png",
            "cus_103.pc.png",
            "cus_104.pc.png",
            "cus_105.pc.png",
            "cus_106.pc.png",
            "cus_107.pc.png",
            "cus_108.pc.png",
            "cus_109.pc.png",
            "cus_110.pc.png",
            "cus_111.pc.png",
            "cus_112.pc.png",
            "cus_113.pc.png",
            "cus_114.pc.png",
            "cus_115.pc.png",
            "cus_116.pc.png",
            "cus_117.pc.png",
            "cus_118.pc.png",
            "proteam.pc.png",
            "trublu.pc.png",
            "noclub.pc.png",
            "unknown.pc.png"
        };
    }
}
